# Generated by Django 3.0.2 on 2020-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comics/%Y/%m/%d')),
                ('title', models.CharField(default='', max_length=255)),
                ('show_title', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('hover_text', models.CharField(default='', max_length=255)),
                ('include_hover_text', models.BooleanField(default=True)),
            ],
        ),
    ]
