# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comics/%Y/%m/%d')),
                ('hover_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Image'),
        ),
    ]
