# Generated by Django 3.0.2 on 2020-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='comic',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='show_description',
            field=models.BooleanField(default=False, help_text='If this is checked, the description will be accessible for this comic. Leave this unchecked to keep the description private.', verbose_name='Show Description'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='hover_text',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Hover Text'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(upload_to='comics/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='include_hover_text',
            field=models.BooleanField(default=True, help_text='If this is checked, the hover text will be displayed when the user hovers their mouse over the comic. Uncheck to disable hover text for this comic.', verbose_name='Include Hover Text'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If this is checked, the title of the comic will be displayed on the web page. Uncheck to hide the title for this comic.', verbose_name='Show Title'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Title'),
        ),
    ]
