# Generated by Django 3.0.2 on 2020-01-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20200104_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='hover_text',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Hover Text'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Title'),
        ),
    ]
