# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20161111_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='include_hover_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='show_title',
            field=models.BooleanField(default=False),
        ),
    ]
