# Generated by Django 3.0.2 on 2020-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20200104_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='num_fb_shares',
            field=models.IntegerField(default=0, verbose_name='Number of FaceBook Shares'),
        ),
        migrations.AddField(
            model_name='comic',
            name='num_inst_shares',
            field=models.IntegerField(default=0, verbose_name='Number of Instagram Shares'),
        ),
        migrations.AddField(
            model_name='comic',
            name='num_shares',
            field=models.IntegerField(default=0, verbose_name='Number of Social Media Shares'),
        ),
        migrations.AddField(
            model_name='comic',
            name='num_tw_shares',
            field=models.IntegerField(default=0, verbose_name='Number of Twitter Shares'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='num_views',
            field=models.IntegerField(default=0, verbose_name='Number of Views'),
        ),
    ]
