# Generated by Django 3.0.2 on 2020-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_auto_20200108_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='is_nsfw',
            field=models.BooleanField(default=False, help_text='If this is checked, the comic is NSFW and will be hidden by default. The user will need to click to reveal the comic.', verbose_name='Is Not Safe For Work?'),
        ),
    ]
